In [1]:
import pandas as pd

In [4]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.22.0-py2.py3-none-any.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 955.1 kB/s eta 0:00:00
Requirement already satisfied: scipy>=1.2.1 in e:\anaconda3\lib\site-packages (from mlxtend) (1.9.1)
Requirement already satisfied: pandas>=0.24.2 in e:\anaconda3\lib\site-packages (from mlxtend) (1.4.4)
Requirement already satisfied: numpy>=1.16.2 in e:\anaconda3\lib\site-packages (from mlxtend) (1.21.5)
Requirement already satisfied: joblib>=0.13.2 in e:\anaconda3\lib\site-packages (from mlxtend) (1.1.0)
Requirement already satisfied: matplotlib>=3.0.0 in e:\anaconda3\lib\site-packages (from mlxtend) (3.5.2)
Requirement already satisfied: setuptools in e:\anaconda3\lib\site-packages (from mlxtend) (63.4.1)
Requirement already satisfied: scikit-learn>=1.0.2 in e:\anaconda3\lib\site-packages (from mlxtend) (1.0.2)
Requirement already satisfied: packaging>=20.0 in e:\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in e:\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in e:\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.2)
Requirement already satisfied: cycler>=0.10 in e:\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in e:\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (9.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in e:\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in e:\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: pytz>=2020.1 in e:\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2022.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in e:\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in e:\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.22.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024D1B0939D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/mlxtend/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024D1B093D00>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/mlxtend/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024D1B093FD0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/mlxtend/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024D1B0BC1F0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/mlxtend/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024D1B0BC3A0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed')': /simple/mlxtend/

In [6]:
from mlxtend.preprocessing import TransactionEncoder

In [8]:
te = TransactionEncoder()

In [38]:
dataset = [['Milk', 'Onion', 'Nutmeg', 'KB', 'Mushroom', 'Yogurt'],
           ['Pulse', 'Onion', 'Nutmeg', 'KB', 'Mushroom', 'Yogurt'],
           ['Milk', 'Apple', 'KB', 'Mushroom'],
           ['Milk', 'Banana', 'Corn', 'KB', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'KB', 'Mushroom', 'Ice-Cream']]

In [39]:
tr = te.fit(dataset).transform(dataset)

In [40]:
df = pd.DataFrame(tr, columns = te.columns_)

In [41]:
df

,Apple,Banana,Corn,Ice-Cream,KB,Milk,Mushroom,Nutmeg,Onion,Pulse,Yogurt
0,False,False,False,False,True,True,True,True,True,False,True
1,False,False,False,False,True,False,True,True,True,True,True
2,True,False,False,False,True,True,True,False,False,False,False
3,False,True,True,False,True,True,False,False,False,False,True
4,False,False,True,True,True,False,True,False,True,False,False

In [42]:
from mlxtend.frequent_patterns import apriori

In [43]:
ar = apriori(df, min_support = 0.6, use_colnames = True)

In [44]:
ar

    support               itemsets
0       1.0                   (KB)
1       0.6                 (Milk)
2       0.8             (Mushroom)
3       0.6                (Onion)
4       0.6               (Yogurt)
5       0.6             (KB, Milk)
6       0.8         (KB, Mushroom)
7       0.6            (KB, Onion)
8       0.6           (KB, Yogurt)
9       0.6      (Mushroom, Onion)
10      0.6  (KB, Mushroom, Onion)

In [45]:
from mlxtend.frequent_patterns import association_rules

In [46]:
asr = association_rules(ar, metric = 'confidence', min_threshold=0.7)

In [47]:
asr

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Milk),(KB),0.6,1.0,0.6,1.00,1.00,0.00,inf,0.0
1,(KB),(Mushroom),1.0,0.8,0.8,0.80,1.00,0.00,1.0,0.0
2,(Mushroom),(KB),0.8,1.0,0.8,1.00,1.00,0.00,inf,0.0
3,(Onion),(KB),0.6,1.0,0.6,1.00,1.00,0.00,inf,0.0
4,(Yogurt),(KB),0.6,1.0,0.6,1.00,1.00,0.00,inf,0.0
5,(Mushroom),(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6,1.0
6,(Onion),(Mushroom),0.6,0.8,0.6,1.00,1.25,0.12,inf,0.5
7,"(KB, Mushroom)",(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6,1.0
8,"(KB, Onion)",(Mushroom),0.6,0.8,0.6,1.00,1.25,0.12,inf,0.5
9,"(Mushroom, Onion)",(KB),0.6,1.0,0.6,1.00,1.00,0.00,inf,0.0
10,(Mushroom),"(KB, Onion)",0.8,0.6,0.6,0.75,1.25,0.12,1.6,1.0
11,(Onion),"(KB, Mushroom)",0.6,0.8,0.6,1.00,1.25,0.12,inf,0.5